/work2/09808/mp46753/frontera/ML_Project/VQGraph/vq.py:283: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled=False)
/work2/09808/mp46753/frontera/ML_Project/VQGraph/vq.py:418: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  @autocast(enabled=False)
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/dataloading/dataloader.py:1144: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py:663: UserWarning: Graph break due to unsupported builtin torch._C._to_dlpack. This function is either a Python builtin (e.g. _warnings.warn) or a third-party C/C++ Python extension (perhaps created with pybind). If it is a Python builtin, please file an issue on GitHub so the PyTorch team can add support for it and see the next case for a workaround. If it is a third-party C/C++ Python extension, please either wrap it into a PyTorch-understood custom operator (see https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html for more details) or, if it is traceable, use torch.compiler.allow_in_graph.
  torch._dynamo.utils.warn_once(msg)
V0421 03:04:25.521153 47548129527040 torch/_dynamo/guards.py:2611] [4/1] [__recompiles] Recompiling function create_unitgraph_from_coo in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph_index.py:1254
V0421 03:04:25.521153 47548129527040 torch/_dynamo/guards.py:2611] [4/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:25.521153 47548129527040 torch/_dynamo/guards.py:2611] [4/1] [__recompiles]     - tensor 'L['row']' dispatch key set mismatch. expected DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), actual DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA)
V0421 03:04:25.536682 47548129527040 torch/_dynamo/guards.py:2611] [5/1] [__recompiles] Recompiling function to_dgl_nd in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/__init__.py:141
V0421 03:04:25.536682 47548129527040 torch/_dynamo/guards.py:2611] [5/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:25.536682 47548129527040 torch/_dynamo/guards.py:2611] [5/1] [__recompiles]     - tensor 'L['data']' dispatch key set mismatch. expected DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), actual DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA)
V0421 03:04:25.545447 47548129527040 torch/_dynamo/guards.py:2611] [6/1] [__recompiles] Recompiling function zerocopy_to_dgl_ndarray in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:432
V0421 03:04:25.545447 47548129527040 torch/_dynamo/guards.py:2611] [6/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:25.545447 47548129527040 torch/_dynamo/guards.py:2611] [6/1] [__recompiles]     - tensor 'L['data']' dispatch key set mismatch. expected DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), actual DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA)
V0421 03:04:25.574816 47548129527040 torch/_dynamo/guards.py:2611] [8/1] [__recompiles] Recompiling function torch_dynamo_resume_in_create_unitgraph_from_coo_at_1296 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph_index.py:1296
V0421 03:04:25.574816 47548129527040 torch/_dynamo/guards.py:2611] [8/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:25.574816 47548129527040 torch/_dynamo/guards.py:2611] [8/1] [__recompiles]     - tensor 'L['col']' dispatch key set mismatch. expected DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), actual DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA)
W0421 03:04:32.827594 47548129527040 torch/_dynamo/variables/tensor.py:715] [30/0] Graph break from `Tensor.item()`, consider setting:
W0421 03:04:32.827594 47548129527040 torch/_dynamo/variables/tensor.py:715] [30/0]     torch._dynamo.config.capture_scalar_outputs = True
W0421 03:04:32.827594 47548129527040 torch/_dynamo/variables/tensor.py:715] [30/0] or:
W0421 03:04:32.827594 47548129527040 torch/_dynamo/variables/tensor.py:715] [30/0]     env TORCHDYNAMO_CAPTURE_SCALAR_OUTPUTS=1
W0421 03:04:32.827594 47548129527040 torch/_dynamo/variables/tensor.py:715] [30/0] to include these operations in the captured graph.
W0421 03:04:32.827594 47548129527040 torch/_dynamo/variables/tensor.py:715] [30/0] 
V0421 03:04:35.832170 47548129527040 torch/_dynamo/guards.py:2611] [4/2] [__recompiles] Recompiling function create_unitgraph_from_coo in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph_index.py:1254
V0421 03:04:35.832170 47548129527040 torch/_dynamo/guards.py:2611] [4/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:35.832170 47548129527040 torch/_dynamo/guards.py:2611] [4/2] [__recompiles]     - tensor 'L['row']' size mismatch at index 0. expected 0, actual 4863
V0421 03:04:35.832170 47548129527040 torch/_dynamo/guards.py:2611] [4/2] [__recompiles]     - tensor 'L['row']' dispatch key set mismatch. expected DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), actual DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA)
V0421 03:04:35.860763 47548129527040 torch/_dynamo/guards.py:2611] [5/2] [__recompiles] Recompiling function to_dgl_nd in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/__init__.py:141
V0421 03:04:35.860763 47548129527040 torch/_dynamo/guards.py:2611] [5/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:35.860763 47548129527040 torch/_dynamo/guards.py:2611] [5/2] [__recompiles]     - tensor 'L['data']' size mismatch at index 0. expected 0, actual 4863
V0421 03:04:35.860763 47548129527040 torch/_dynamo/guards.py:2611] [5/2] [__recompiles]     - tensor 'L['data']' dispatch key set mismatch. expected DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), actual DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA)
V0421 03:04:35.873453 47548129527040 torch/_dynamo/guards.py:2611] [6/2] [__recompiles] Recompiling function zerocopy_to_dgl_ndarray in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:432
V0421 03:04:35.873453 47548129527040 torch/_dynamo/guards.py:2611] [6/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:35.873453 47548129527040 torch/_dynamo/guards.py:2611] [6/2] [__recompiles]     - tensor 'L['data']' size mismatch at index 0. expected 0, actual 4863
V0421 03:04:35.873453 47548129527040 torch/_dynamo/guards.py:2611] [6/2] [__recompiles]     - tensor 'L['data']' dispatch key set mismatch. expected DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), actual DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA)
V0421 03:04:35.912465 47548129527040 torch/_dynamo/guards.py:2611] [8/2] [__recompiles] Recompiling function torch_dynamo_resume_in_create_unitgraph_from_coo_at_1296 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph_index.py:1296
V0421 03:04:35.912465 47548129527040 torch/_dynamo/guards.py:2611] [8/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:35.912465 47548129527040 torch/_dynamo/guards.py:2611] [8/2] [__recompiles]     - tensor 'L['col']' size mismatch at index 0. expected 0, actual 4863
V0421 03:04:35.912465 47548129527040 torch/_dynamo/guards.py:2611] [8/2] [__recompiles]     - tensor 'L['col']' dispatch key set mismatch. expected DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), actual DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA)
V0421 03:04:35.929216 47548129527040 torch/_dynamo/guards.py:2611] [32/1] [__recompiles] Recompiling function torch_dynamo_resume_in_add_edges_at_574 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:574
V0421 03:04:35.929216 47548129527040 torch/_dynamo/guards.py:2611] [32/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:35.929216 47548129527040 torch/_dynamo/guards.py:2611] [32/1] [__recompiles]     - L['___stack0'] == 3397                                      
V0421 03:04:36.151677 47548129527040 torch/_dynamo/guards.py:2611] [34/1] [__recompiles] Recompiling function cat in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:222
V0421 03:04:36.151677 47548129527040 torch/_dynamo/guards.py:2611] [34/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:36.151677 47548129527040 torch/_dynamo/guards.py:2611] [34/1] [__recompiles]     - tensor 'L['seq'][0]' size mismatch at index 0. expected 0, actual 4863
V0421 03:04:36.898171 47548129527040 torch/_dynamo/guards.py:2611] [20/1] [__recompiles] Recompiling function add_edges in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:435
V0421 03:04:36.898171 47548129527040 torch/_dynamo/guards.py:2611] [20/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:36.898171 47548129527040 torch/_dynamo/guards.py:2611] [20/1] [__recompiles]     - tensor 'L['u']' size mismatch at index 0. expected 4863, actual 973
V0421 03:04:36.919624 47548129527040 torch/_dynamo/guards.py:2611] [26/1] [__recompiles] Recompiling function torch_dynamo_resume_in_add_edges_at_541 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:541
V0421 03:04:36.919624 47548129527040 torch/_dynamo/guards.py:2611] [26/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:36.919624 47548129527040 torch/_dynamo/guards.py:2611] [26/1] [__recompiles]     - tensor 'L['v']' size mismatch at index 0. expected 4863, actual 973
V0421 03:04:36.947128 47548129527040 torch/_dynamo/guards.py:2611] [27/1] [__recompiles] Recompiling function torch_dynamo_resume_in_add_edges_at_542 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:542
V0421 03:04:36.947128 47548129527040 torch/_dynamo/guards.py:2611] [27/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:36.947128 47548129527040 torch/_dynamo/guards.py:2611] [27/1] [__recompiles]     - tensor 'L['___stack0']' size mismatch at index 0. expected 4863, actual 973
V0421 03:04:36.963678 47548129527040 torch/_dynamo/guards.py:2611] [28/1] [__recompiles] Recompiling function torch_dynamo_resume_in_add_edges_at_545 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:545
V0421 03:04:36.963678 47548129527040 torch/_dynamo/guards.py:2611] [28/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:36.963678 47548129527040 torch/_dynamo/guards.py:2611] [28/1] [__recompiles]     - tensor 'L['u']' size mismatch at index 0. expected 4863, actual 973
V0421 03:04:37.032316 47548129527040 torch/_dynamo/guards.py:2611] [30/1] [__recompiles] Recompiling function torch_dynamo_resume_in_add_edges_at_573 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:573
V0421 03:04:37.032316 47548129527040 torch/_dynamo/guards.py:2611] [30/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:37.032316 47548129527040 torch/_dynamo/guards.py:2611] [30/1] [__recompiles]     - tensor 'L['u']' size mismatch at index 0. expected 4863, actual 973
V0421 03:04:37.289235 47548129527040 torch/_dynamo/guards.py:2611] [32/2] [__recompiles] Recompiling function torch_dynamo_resume_in_add_edges_at_574 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:574
V0421 03:04:37.289235 47548129527040 torch/_dynamo/guards.py:2611] [32/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:37.289235 47548129527040 torch/_dynamo/guards.py:2611] [32/2] [__recompiles]     - tensor 'L['v']' size mismatch at index 0. expected 4863, actual 973
V0421 03:04:37.289235 47548129527040 torch/_dynamo/guards.py:2611] [32/2] [__recompiles]     - L['___stack0'] == 3397                                      
V0421 03:04:37.539208 47548129527040 torch/_dynamo/guards.py:2611] [34/2] [__recompiles] Recompiling function cat in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:222
V0421 03:04:37.539208 47548129527040 torch/_dynamo/guards.py:2611] [34/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:37.539208 47548129527040 torch/_dynamo/guards.py:2611] [34/2] [__recompiles]     - tensor 'L['seq'][1]' size mismatch at index 0. expected 4863, actual 973
V0421 03:04:37.539208 47548129527040 torch/_dynamo/guards.py:2611] [34/2] [__recompiles]     - tensor 'L['seq'][0]' size mismatch at index 0. expected 0, actual 9726
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py:663: UserWarning: Graph break due to unsupported builtin posix.stat. This function is either a Python builtin (e.g. _warnings.warn) or a third-party C/C++ Python extension (perhaps created with pybind). If it is a Python builtin, please file an issue on GitHub so the PyTorch team can add support for it and see the next case for a workaround. If it is a third-party C/C++ Python extension, please either wrap it into a PyTorch-understood custom operator (see https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html for more details) or, if it is traceable, use torch.compiler.allow_in_graph.
  torch._dynamo.utils.warn_once(msg)
V0421 03:04:41.828906 47548129527040 torch/_dynamo/guards.py:2611] [6/3] [__recompiles] Recompiling function zerocopy_to_dgl_ndarray in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:432
V0421 03:04:41.828906 47548129527040 torch/_dynamo/guards.py:2611] [6/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:41.828906 47548129527040 torch/_dynamo/guards.py:2611] [6/3] [__recompiles]     - GLOBAL_STATE changed: grad_mode 
V0421 03:04:41.828906 47548129527040 torch/_dynamo/guards.py:2611] [6/3] [__recompiles]     - GLOBAL_STATE changed: grad_mode 
V0421 03:04:41.828906 47548129527040 torch/_dynamo/guards.py:2611] [6/3] [__recompiles]     - GLOBAL_STATE changed: grad_mode 
V0421 03:04:41.875973 47548129527040 torch/_dynamo/guards.py:2611] [7/1] [__recompiles] Recompiling function torch_dynamo_resume_in_zerocopy_to_dgl_ndarray_at_435 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:435
V0421 03:04:41.875973 47548129527040 torch/_dynamo/guards.py:2611] [7/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:41.875973 47548129527040 torch/_dynamo/guards.py:2611] [7/1] [__recompiles]     - GLOBAL_STATE changed: grad_mode 
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/torch/_dynamo/variables/functions.py:663: UserWarning: Graph break due to unsupported builtin time.perf_counter. This function is either a Python builtin (e.g. _warnings.warn) or a third-party C/C++ Python extension (perhaps created with pybind). If it is a Python builtin, please file an issue on GitHub so the PyTorch team can add support for it and see the next case for a workaround. If it is a third-party C/C++ Python extension, please either wrap it into a PyTorch-understood custom operator (see https://pytorch.org/tutorials/advanced/custom_ops_landing_page.html for more details) or, if it is traceable, use torch.compiler.allow_in_graph.
  torch._dynamo.utils.warn_once(msg)
V0421 03:04:42.131805 47548129527040 torch/_dynamo/guards.py:2611] [86/1] [__recompiles] Recompiling function torch_dynamo_resume_in_hook_at_12 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/benchmark_utils.py:12
V0421 03:04:42.131805 47548129527040 torch/_dynamo/guards.py:2611] [86/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:42.131805 47548129527040 torch/_dynamo/guards.py:2611] [86/1] [__recompiles]     - L['___stack0'] == 926123.603687657                          
V0421 03:04:42.227521 47548129527040 torch/_dynamo/guards.py:2611] [86/2] [__recompiles] Recompiling function torch_dynamo_resume_in_hook_at_12 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/benchmark_utils.py:12
V0421 03:04:42.227521 47548129527040 torch/_dynamo/guards.py:2611] [86/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:42.227521 47548129527040 torch/_dynamo/guards.py:2611] [86/2] [__recompiles]     - L['___stack0'] == 926123.616683064                          
V0421 03:04:42.227521 47548129527040 torch/_dynamo/guards.py:2611] [86/2] [__recompiles]     - L['___stack0'] == 926123.603687657                          
V0421 03:04:45.433816 47548129527040 torch/_dynamo/guards.py:2611] [86/3] [__recompiles] Recompiling function torch_dynamo_resume_in_hook_at_12 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/benchmark_utils.py:12
V0421 03:04:45.433816 47548129527040 torch/_dynamo/guards.py:2611] [86/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:45.433816 47548129527040 torch/_dynamo/guards.py:2611] [86/3] [__recompiles]     - L['___stack0'] == 926123.712404017                          
V0421 03:04:45.433816 47548129527040 torch/_dynamo/guards.py:2611] [86/3] [__recompiles]     - L['___stack0'] == 926123.616683064                          
V0421 03:04:45.433816 47548129527040 torch/_dynamo/guards.py:2611] [86/3] [__recompiles]     - L['___stack0'] == 926123.603687657                          
V0421 03:04:47.000346 47548129527040 torch/_dynamo/guards.py:2611] [86/4] [__recompiles] Recompiling function torch_dynamo_resume_in_hook_at_12 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/benchmark_utils.py:12
V0421 03:04:47.000346 47548129527040 torch/_dynamo/guards.py:2611] [86/4] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.000346 47548129527040 torch/_dynamo/guards.py:2611] [86/4] [__recompiles]     - L['___stack0'] == 926126.918527678                          
V0421 03:04:47.000346 47548129527040 torch/_dynamo/guards.py:2611] [86/4] [__recompiles]     - L['___stack0'] == 926123.712404017                          
V0421 03:04:47.000346 47548129527040 torch/_dynamo/guards.py:2611] [86/4] [__recompiles]     - L['___stack0'] == 926123.616683064                          
V0421 03:04:47.000346 47548129527040 torch/_dynamo/guards.py:2611] [86/4] [__recompiles]     - L['___stack0'] == 926123.603687657                          
V0421 03:04:47.380812 47548129527040 torch/_dynamo/guards.py:2611] [86/5] [__recompiles] Recompiling function torch_dynamo_resume_in_hook_at_12 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/benchmark_utils.py:12
V0421 03:04:47.380812 47548129527040 torch/_dynamo/guards.py:2611] [86/5] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.380812 47548129527040 torch/_dynamo/guards.py:2611] [86/5] [__recompiles]     - L['___stack0'] == 926128.48507501                           
V0421 03:04:47.380812 47548129527040 torch/_dynamo/guards.py:2611] [86/5] [__recompiles]     - L['___stack0'] == 926126.918527678                          
V0421 03:04:47.380812 47548129527040 torch/_dynamo/guards.py:2611] [86/5] [__recompiles]     - L['___stack0'] == 926123.712404017                          
V0421 03:04:47.380812 47548129527040 torch/_dynamo/guards.py:2611] [86/5] [__recompiles]     - L['___stack0'] == 926123.616683064                          
V0421 03:04:47.380812 47548129527040 torch/_dynamo/guards.py:2611] [86/5] [__recompiles]     - L['___stack0'] == 926123.603687657                          
V0421 03:04:47.387067 47548129527040 torch/_dynamo/guards.py:2611] [86/6] [__recompiles] Recompiling function torch_dynamo_resume_in_hook_at_12 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/benchmark_utils.py:12
V0421 03:04:47.387067 47548129527040 torch/_dynamo/guards.py:2611] [86/6] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.387067 47548129527040 torch/_dynamo/guards.py:2611] [86/6] [__recompiles]     - L['___stack0'] == 926128.865621324                          
V0421 03:04:47.387067 47548129527040 torch/_dynamo/guards.py:2611] [86/6] [__recompiles]     - L['___stack0'] == 926128.48507501                           
V0421 03:04:47.387067 47548129527040 torch/_dynamo/guards.py:2611] [86/6] [__recompiles]     - L['___stack0'] == 926126.918527678                          
V0421 03:04:47.387067 47548129527040 torch/_dynamo/guards.py:2611] [86/6] [__recompiles]     - L['___stack0'] == 926123.712404017                          
V0421 03:04:47.387067 47548129527040 torch/_dynamo/guards.py:2611] [86/6] [__recompiles]     - L['___stack0'] == 926123.616683064                          
V0421 03:04:47.387067 47548129527040 torch/_dynamo/guards.py:2611] [86/6] [__recompiles]     - L['___stack0'] == 926123.603687657                          
V0421 03:04:47.443172 47548129527040 torch/_dynamo/guards.py:2611] [57/1] [__recompiles] Recompiling function __setitem__ in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/view.py:82
V0421 03:04:47.443172 47548129527040 torch/_dynamo/guards.py:2611] [57/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.443172 47548129527040 torch/_dynamo/guards.py:2611] [57/1] [__recompiles]     - tensor 'L['val']' requires_grad mismatch. expected requires_grad=0
V0421 03:04:47.464937 47548129527040 torch/_dynamo/guards.py:2611] [61/1] [__recompiles] Recompiling function __setitem__ in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:690
V0421 03:04:47.464937 47548129527040 torch/_dynamo/guards.py:2611] [61/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.464937 47548129527040 torch/_dynamo/guards.py:2611] [61/1] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=0
V0421 03:04:47.484052 47548129527040 torch/_dynamo/guards.py:2611] [62/1] [__recompiles] Recompiling function update_column in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:772
V0421 03:04:47.484052 47548129527040 torch/_dynamo/guards.py:2611] [62/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.484052 47548129527040 torch/_dynamo/guards.py:2611] [62/1] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=0
V0421 03:04:47.503589 47548129527040 torch/_dynamo/guards.py:2611] [63/1] [__recompiles] Recompiling function create in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:472
V0421 03:04:47.503589 47548129527040 torch/_dynamo/guards.py:2611] [63/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.503589 47548129527040 torch/_dynamo/guards.py:2611] [63/1] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=0
V0421 03:04:47.521873 47548129527040 torch/_dynamo/guards.py:2611] [64/1] [__recompiles] Recompiling function __init__ in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:210
V0421 03:04:47.521873 47548129527040 torch/_dynamo/guards.py:2611] [64/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.521873 47548129527040 torch/_dynamo/guards.py:2611] [64/1] [__recompiles]     - tensor 'L['storage']' requires_grad mismatch. expected requires_grad=0
V0421 03:04:47.541312 47548129527040 torch/_dynamo/guards.py:2611] [65/1] [__recompiles] Recompiling function infer_scheme in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:151
V0421 03:04:47.541312 47548129527040 torch/_dynamo/guards.py:2611] [65/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.541312 47548129527040 torch/_dynamo/guards.py:2611] [65/1] [__recompiles]     - tensor 'L['tensor']' requires_grad mismatch. expected requires_grad=0
V0421 03:04:47.586104 47548129527040 torch/_dynamo/guards.py:2611] [68/1] [__recompiles] Recompiling function func in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/ops/spmm.py:213
V0421 03:04:47.586104 47548129527040 torch/_dynamo/guards.py:2611] [68/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.586104 47548129527040 torch/_dynamo/guards.py:2611] [68/1] [__recompiles]     - tensor 'L['x']' requires_grad mismatch. expected requires_grad=0
V0421 03:04:47.599602 47548129527040 torch/_dynamo/guards.py:2611] [70/1] [__recompiles] Recompiling function torch_dynamo_resume_in_gspmm_at_75 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/ops/spmm.py:75
V0421 03:04:47.599602 47548129527040 torch/_dynamo/guards.py:2611] [70/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.599602 47548129527040 torch/_dynamo/guards.py:2611] [70/1] [__recompiles]     - tensor 'L['lhs_data']' requires_grad mismatch. expected requires_grad=0
V0421 03:04:47.617372 47548129527040 torch/_dynamo/guards.py:2611] [74/1] [__recompiles] Recompiling function forward in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/sparse.py:163
V0421 03:04:47.617372 47548129527040 torch/_dynamo/guards.py:2611] [74/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.617372 47548129527040 torch/_dynamo/guards.py:2611] [74/1] [__recompiles]     - tensor 'L['X']' requires_grad mismatch. expected requires_grad=0
V0421 03:04:47.633495 47548129527040 torch/_dynamo/guards.py:2611] [77/1] [__recompiles] Recompiling function zeros in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:287
V0421 03:04:47.633495 47548129527040 torch/_dynamo/guards.py:2611] [77/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.633495 47548129527040 torch/_dynamo/guards.py:2611] [77/1] [__recompiles]     - L['shape'][1] == 767                                        
V0421 03:04:47.906714 47548129527040 torch/_dynamo/guards.py:2611] [6/4] [__recompiles] Recompiling function zerocopy_to_dgl_ndarray in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:432
V0421 03:04:47.906714 47548129527040 torch/_dynamo/guards.py:2611] [6/4] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.906714 47548129527040 torch/_dynamo/guards.py:2611] [6/4] [__recompiles]     - GLOBAL_STATE changed: grad_mode 
V0421 03:04:47.906714 47548129527040 torch/_dynamo/guards.py:2611] [6/4] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=0
V0421 03:04:47.906714 47548129527040 torch/_dynamo/guards.py:2611] [6/4] [__recompiles]     - GLOBAL_STATE changed: grad_mode 
V0421 03:04:47.906714 47548129527040 torch/_dynamo/guards.py:2611] [6/4] [__recompiles]     - GLOBAL_STATE changed: grad_mode 
V0421 03:04:47.954795 47548129527040 torch/_dynamo/guards.py:2611] [79/1] [__recompiles] Recompiling function zerocopy_to_dgl_ndarray_for_write in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:454
V0421 03:04:47.954795 47548129527040 torch/_dynamo/guards.py:2611] [79/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.954795 47548129527040 torch/_dynamo/guards.py:2611] [79/1] [__recompiles]     - tensor 'L['input']' stride mismatch at index 0. expected 767, actual 128
V0421 03:04:47.991616 47548129527040 torch/_dynamo/guards.py:2611] [80/1] [__recompiles] Recompiling function check_is_view in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:441
V0421 03:04:47.991616 47548129527040 torch/_dynamo/guards.py:2611] [80/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:47.991616 47548129527040 torch/_dynamo/guards.py:2611] [80/1] [__recompiles]     - tensor 'L['input']' stride mismatch at index 0. expected 767, actual 128
V0421 03:04:48.001750 47548129527040 torch/_dynamo/guards.py:2611] [81/1] [__recompiles] Recompiling function torch_dynamo_resume_in_check_is_view_at_443 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:443
V0421 03:04:48.001750 47548129527040 torch/_dynamo/guards.py:2611] [81/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:48.001750 47548129527040 torch/_dynamo/guards.py:2611] [81/1] [__recompiles]     - tensor 'L['input']' stride mismatch at index 0. expected 767, actual 128
V0421 03:04:48.013201 47548129527040 torch/_dynamo/guards.py:2611] [82/1] [__recompiles] Recompiling function torch_dynamo_resume_in_zerocopy_to_dgl_ndarray_for_write_at_461 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:461
V0421 03:04:48.013201 47548129527040 torch/_dynamo/guards.py:2611] [82/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:48.013201 47548129527040 torch/_dynamo/guards.py:2611] [82/1] [__recompiles]     - tensor 'L['input']' stride mismatch at index 0. expected 767, actual 128
V0421 03:04:48.027705 47548129527040 torch/_dynamo/guards.py:2611] [83/1] [__recompiles] Recompiling function torch_dynamo_resume_in_forward_at_165 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/sparse.py:165
V0421 03:04:48.027705 47548129527040 torch/_dynamo/guards.py:2611] [83/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:48.027705 47548129527040 torch/_dynamo/guards.py:2611] [83/1] [__recompiles]     - tensor 'L['X']' requires_grad mismatch. expected requires_grad=0
V0421 03:04:48.066679 47548129527040 torch/_dynamo/guards.py:2611] [86/7] [__recompiles] Recompiling function torch_dynamo_resume_in_hook_at_12 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/benchmark_utils.py:12
V0421 03:04:48.066679 47548129527040 torch/_dynamo/guards.py:2611] [86/7] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:48.066679 47548129527040 torch/_dynamo/guards.py:2611] [86/7] [__recompiles]     - L['___stack0'] == 926128.871898186                          
V0421 03:04:48.066679 47548129527040 torch/_dynamo/guards.py:2611] [86/7] [__recompiles]     - L['___stack0'] == 926128.865621324                          
V0421 03:04:48.066679 47548129527040 torch/_dynamo/guards.py:2611] [86/7] [__recompiles]     - L['___stack0'] == 926128.48507501                           
V0421 03:04:48.066679 47548129527040 torch/_dynamo/guards.py:2611] [86/7] [__recompiles]     - L['___stack0'] == 926126.918527678                          
V0421 03:04:48.066679 47548129527040 torch/_dynamo/guards.py:2611] [86/7] [__recompiles]     - L['___stack0'] == 926123.712404017                          
V0421 03:04:48.066679 47548129527040 torch/_dynamo/guards.py:2611] [86/7] [__recompiles]     - L['___stack0'] == 926123.616683064                          
V0421 03:04:48.066679 47548129527040 torch/_dynamo/guards.py:2611] [86/7] [__recompiles]     - L['___stack0'] == 926123.603687657                          
V0421 03:04:48.073024 47548129527040 torch/_dynamo/guards.py:2611] [86/8] [__recompiles] Recompiling function torch_dynamo_resume_in_hook_at_12 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/benchmark_utils.py:12
V0421 03:04:48.073024 47548129527040 torch/_dynamo/guards.py:2611] [86/8] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:48.073024 47548129527040 torch/_dynamo/guards.py:2611] [86/8] [__recompiles]     - L['___stack0'] == 926129.551448191                          
V0421 03:04:48.073024 47548129527040 torch/_dynamo/guards.py:2611] [86/8] [__recompiles]     - L['___stack0'] == 926128.871898186                          
V0421 03:04:48.073024 47548129527040 torch/_dynamo/guards.py:2611] [86/8] [__recompiles]     - L['___stack0'] == 926128.865621324                          
V0421 03:04:48.073024 47548129527040 torch/_dynamo/guards.py:2611] [86/8] [__recompiles]     - L['___stack0'] == 926128.48507501                           
V0421 03:04:48.073024 47548129527040 torch/_dynamo/guards.py:2611] [86/8] [__recompiles]     - L['___stack0'] == 926126.918527678                          
V0421 03:04:48.073024 47548129527040 torch/_dynamo/guards.py:2611] [86/8] [__recompiles]     - L['___stack0'] == 926123.712404017                          
V0421 03:04:48.073024 47548129527040 torch/_dynamo/guards.py:2611] [86/8] [__recompiles]     - L['___stack0'] == 926123.616683064                          
V0421 03:04:48.073024 47548129527040 torch/_dynamo/guards.py:2611] [86/8] [__recompiles]     - L['___stack0'] == 926123.603687657                          
W0421 03:04:48.073164 47548129527040 torch/_dynamo/convert_frame.py:762] [86/8] torch._dynamo hit config.cache_size_limit (8)
W0421 03:04:48.073164 47548129527040 torch/_dynamo/convert_frame.py:762] [86/8]    function: 'torch_dynamo_resume_in_hook_at_12' (/work2/09808/mp46753/frontera/ML_Project/VQGraph/benchmark_utils.py:12)
W0421 03:04:48.073164 47548129527040 torch/_dynamo/convert_frame.py:762] [86/8]    last reason: L['___stack0'] == 926123.603687657                          
W0421 03:04:48.073164 47548129527040 torch/_dynamo/convert_frame.py:762] [86/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W0421 03:04:48.073164 47548129527040 torch/_dynamo/convert_frame.py:762] [86/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/dataloading/dataloader.py:1144: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
V0421 03:04:49.884962 47548129527040 torch/_dynamo/guards.py:2611] [0/1] [__recompiles] Recompiling function forward in /work2/09808/mp46753/frontera/ML_Project/VQGraph/models.py:449
V0421 03:04:49.884962 47548129527040 torch/_dynamo/guards.py:2611] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:49.884962 47548129527040 torch/_dynamo/guards.py:2611] [0/1] [__recompiles]     - tensor 'L['feats']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:49.912411 47548129527040 torch/_dynamo/guards.py:2611] [1/1] [__recompiles] Recompiling function forward in /work2/09808/mp46753/frontera/ML_Project/VQGraph/models.py:154
V0421 03:04:49.912411 47548129527040 torch/_dynamo/guards.py:2611] [1/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:49.912411 47548129527040 torch/_dynamo/guards.py:2611] [1/1] [__recompiles]     - tensor 'L['feats']' size mismatch at index 0. expected 3398, actual 3415
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
V0421 03:04:49.928224 47548129527040 torch/_dynamo/guards.py:2611] [9/1] [__recompiles] Recompiling function torch_dynamo_resume_in_forward_at_157 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/models.py:157
V0421 03:04:49.928224 47548129527040 torch/_dynamo/guards.py:2611] [9/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:49.928224 47548129527040 torch/_dynamo/guards.py:2611] [9/1] [__recompiles]     - tensor 'L['h']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:49.943105 47548129527040 torch/_dynamo/guards.py:2611] [13/1] [__recompiles] Recompiling function torch_dynamo_resume_in_forward_at_157 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/models.py:157
V0421 03:04:49.943105 47548129527040 torch/_dynamo/guards.py:2611] [13/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:49.943105 47548129527040 torch/_dynamo/guards.py:2611] [13/1] [__recompiles]     - tensor 'L['h']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:49.984375 47548129527040 torch/_dynamo/guards.py:2611] [4/3] [__recompiles] Recompiling function create_unitgraph_from_coo in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph_index.py:1254
V0421 03:04:49.984375 47548129527040 torch/_dynamo/guards.py:2611] [4/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:49.984375 47548129527040 torch/_dynamo/guards.py:2611] [4/3] [__recompiles]     - tensor 'L['row']' dispatch key set mismatch. expected DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), actual DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA)
V0421 03:04:49.984375 47548129527040 torch/_dynamo/guards.py:2611] [4/3] [__recompiles]     - L['num_dst'] == 3398                                        
V0421 03:04:49.984375 47548129527040 torch/_dynamo/guards.py:2611] [4/3] [__recompiles]     - L['num_dst'] == 3398                                        
V0421 03:04:50.016551 47548129527040 torch/_dynamo/guards.py:2611] [8/3] [__recompiles] Recompiling function torch_dynamo_resume_in_create_unitgraph_from_coo_at_1296 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph_index.py:1296
V0421 03:04:50.016551 47548129527040 torch/_dynamo/guards.py:2611] [8/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:50.016551 47548129527040 torch/_dynamo/guards.py:2611] [8/3] [__recompiles]     - tensor 'L['col']' dispatch key set mismatch. expected DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), actual DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA)
V0421 03:04:50.016551 47548129527040 torch/_dynamo/guards.py:2611] [8/3] [__recompiles]     - L['___stack2'] == 3398                                      
V0421 03:04:50.016551 47548129527040 torch/_dynamo/guards.py:2611] [8/3] [__recompiles]     - L['___stack2'] == 3398                                      
V0421 03:04:50.030349 47548129527040 torch/_dynamo/guards.py:2611] [15/1] [__recompiles] Recompiling function _dispatch in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/utils/internal.py:65
V0421 03:04:50.030349 47548129527040 torch/_dynamo/guards.py:2611] [15/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:50.030349 47548129527040 torch/_dynamo/guards.py:2611] [15/1] [__recompiles]     - L['data'][0] == 3398                                        
V0421 03:04:53.316457 47548129527040 torch/_dynamo/guards.py:2611] [29/1] [__recompiles] Recompiling function torch_dynamo_resume_in_add_edges_at_572 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:572
V0421 03:04:53.316457 47548129527040 torch/_dynamo/guards.py:2611] [29/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:53.316457 47548129527040 torch/_dynamo/guards.py:2611] [29/1] [__recompiles]     - L['___stack0'] == 3398                                      
V0421 03:04:53.334125 47548129527040 torch/_dynamo/guards.py:2611] [30/2] [__recompiles] Recompiling function torch_dynamo_resume_in_add_edges_at_573 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:573
V0421 03:04:53.334125 47548129527040 torch/_dynamo/guards.py:2611] [30/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:53.334125 47548129527040 torch/_dynamo/guards.py:2611] [30/2] [__recompiles]     - L['___stack0'] == 3398                                      
V0421 03:04:53.334125 47548129527040 torch/_dynamo/guards.py:2611] [30/2] [__recompiles]     - tensor 'L['u']' size mismatch at index 0. expected 4863, actual 4828
V0421 03:04:53.730535 47548129527040 torch/_dynamo/guards.py:2611] [34/3] [__recompiles] Recompiling function cat in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:222
V0421 03:04:53.730535 47548129527040 torch/_dynamo/guards.py:2611] [34/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:53.730535 47548129527040 torch/_dynamo/guards.py:2611] [34/3] [__recompiles]     - 2 <= L['seq'][0].size()[0] <= 2147483645                      # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:04:53.730535 47548129527040 torch/_dynamo/guards.py:2611] [34/3] [__recompiles]     - tensor 'L['seq'][1]' size mismatch at index 0. expected 4863, actual 4828
V0421 03:04:53.730535 47548129527040 torch/_dynamo/guards.py:2611] [34/3] [__recompiles]     - tensor 'L['seq'][1]' size mismatch at index 0. expected 4863, actual 4828
V0421 03:04:54.058640 47548129527040 torch/_dynamo/guards.py:2611] [4/4] [__recompiles] Recompiling function create_unitgraph_from_coo in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph_index.py:1254
V0421 03:04:54.058640 47548129527040 torch/_dynamo/guards.py:2611] [4/4] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:54.058640 47548129527040 torch/_dynamo/guards.py:2611] [4/4] [__recompiles]     - tensor 'L['row']' size mismatch at index 0. expected 0, actual 4828
V0421 03:04:54.058640 47548129527040 torch/_dynamo/guards.py:2611] [4/4] [__recompiles]     - tensor 'L['row']' dispatch key set mismatch. expected DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), actual DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA)
V0421 03:04:54.058640 47548129527040 torch/_dynamo/guards.py:2611] [4/4] [__recompiles]     - L['num_dst'] == 3398                                        
V0421 03:04:54.058640 47548129527040 torch/_dynamo/guards.py:2611] [4/4] [__recompiles]     - tensor 'L['row']' size mismatch at index 0. expected 0, actual 4828
V0421 03:04:54.100564 47548129527040 torch/_dynamo/guards.py:2611] [8/4] [__recompiles] Recompiling function torch_dynamo_resume_in_create_unitgraph_from_coo_at_1296 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph_index.py:1296
V0421 03:04:54.100564 47548129527040 torch/_dynamo/guards.py:2611] [8/4] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:54.100564 47548129527040 torch/_dynamo/guards.py:2611] [8/4] [__recompiles]     - tensor 'L['col']' size mismatch at index 0. expected 0, actual 4828
V0421 03:04:54.100564 47548129527040 torch/_dynamo/guards.py:2611] [8/4] [__recompiles]     - tensor 'L['col']' dispatch key set mismatch. expected DispatchKeySet(CPU, BackendSelect, ADInplaceOrView, AutogradCPU), actual DispatchKeySet(CUDA, BackendSelect, ADInplaceOrView, AutogradCUDA)
V0421 03:04:54.100564 47548129527040 torch/_dynamo/guards.py:2611] [8/4] [__recompiles]     - L['___stack2'] == 3398                                      
V0421 03:04:54.100564 47548129527040 torch/_dynamo/guards.py:2611] [8/4] [__recompiles]     - tensor 'L['col']' size mismatch at index 0. expected 0, actual 4828
V0421 03:04:54.121274 47548129527040 torch/_dynamo/guards.py:2611] [41/1] [__recompiles] Recompiling function spmatrix in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/sparse/sparse_matrix.py:763
V0421 03:04:54.121274 47548129527040 torch/_dynamo/guards.py:2611] [41/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:54.121274 47548129527040 torch/_dynamo/guards.py:2611] [41/1] [__recompiles]     - tensor 'L['indices']' stride mismatch at index 0. expected 11672, actual 11602
V0421 03:04:54.474466 47548129527040 torch/_dynamo/guards.py:2611] [47/1] [__recompiles] Recompiling function arange in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:406
V0421 03:04:54.474466 47548129527040 torch/_dynamo/guards.py:2611] [47/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:54.474466 47548129527040 torch/_dynamo/guards.py:2611] [47/1] [__recompiles]     - L['stop'] == 3398                                           
V0421 03:04:54.789564 47548129527040 torch/_dynamo/guards.py:2611] [48/1] [__recompiles] Recompiling function in_degrees in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph_index.py:702
V0421 03:04:54.789564 47548129527040 torch/_dynamo/guards.py:2611] [48/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:54.789564 47548129527040 torch/_dynamo/guards.py:2611] [48/1] [__recompiles]     - tensor 'L['v']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:54.807210 47548129527040 torch/_dynamo/guards.py:2611] [50/1] [__recompiles] Recompiling function has_nodes in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:2878
V0421 03:04:54.807210 47548129527040 torch/_dynamo/guards.py:2611] [50/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:54.807210 47548129527040 torch/_dynamo/guards.py:2611] [50/1] [__recompiles]     - tensor 'L['vid']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:54.823247 47548129527040 torch/_dynamo/guards.py:2611] [51/1] [__recompiles] Recompiling function torch_dynamo_resume_in_has_nodes_at_2925 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:2925
V0421 03:04:54.823247 47548129527040 torch/_dynamo/guards.py:2611] [51/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:54.823247 47548129527040 torch/_dynamo/guards.py:2611] [51/1] [__recompiles]     - tensor 'L['___stack0']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.056296 47548129527040 torch/_dynamo/guards.py:2611] [52/1] [__recompiles] Recompiling function torch_dynamo_resume_in_has_nodes_at_2926 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:2926
V0421 03:04:55.056296 47548129527040 torch/_dynamo/guards.py:2611] [52/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.056296 47548129527040 torch/_dynamo/guards.py:2611] [52/1] [__recompiles]     - tensor 'L['vid_tensor']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.079339 47548129527040 torch/_dynamo/guards.py:2611] [53/1] [__recompiles] Recompiling function has_nodes in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph_index.py:444
V0421 03:04:55.079339 47548129527040 torch/_dynamo/guards.py:2611] [53/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.079339 47548129527040 torch/_dynamo/guards.py:2611] [53/1] [__recompiles]     - tensor 'L['vids']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.097018 47548129527040 torch/_dynamo/guards.py:2611] [54/1] [__recompiles] Recompiling function torch_dynamo_resume_in_has_nodes_at_2930 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:2930
V0421 03:04:55.097018 47548129527040 torch/_dynamo/guards.py:2611] [54/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.097018 47548129527040 torch/_dynamo/guards.py:2611] [54/1] [__recompiles]     - tensor 'L['___stack0']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.413725 47548129527040 torch/_dynamo/guards.py:2611] [55/1] [__recompiles] Recompiling function sum in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:152
V0421 03:04:55.413725 47548129527040 torch/_dynamo/guards.py:2611] [55/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.413725 47548129527040 torch/_dynamo/guards.py:2611] [55/1] [__recompiles]     - tensor 'L['input']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.498596 47548129527040 torch/_dynamo/guards.py:2611] [57/2] [__recompiles] Recompiling function __setitem__ in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/view.py:82
V0421 03:04:55.498596 47548129527040 torch/_dynamo/guards.py:2611] [57/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.498596 47548129527040 torch/_dynamo/guards.py:2611] [57/2] [__recompiles]     - tensor 'L['val']' requires_grad mismatch. expected requires_grad=1
V0421 03:04:55.498596 47548129527040 torch/_dynamo/guards.py:2611] [57/2] [__recompiles]     - tensor 'L['val']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.517513 47548129527040 torch/_dynamo/guards.py:2611] [61/2] [__recompiles] Recompiling function __setitem__ in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:690
V0421 03:04:55.517513 47548129527040 torch/_dynamo/guards.py:2611] [61/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.517513 47548129527040 torch/_dynamo/guards.py:2611] [61/2] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=1
V0421 03:04:55.517513 47548129527040 torch/_dynamo/guards.py:2611] [61/2] [__recompiles]     - tensor 'L['data']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.535651 47548129527040 torch/_dynamo/guards.py:2611] [62/2] [__recompiles] Recompiling function update_column in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:772
V0421 03:04:55.535651 47548129527040 torch/_dynamo/guards.py:2611] [62/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.535651 47548129527040 torch/_dynamo/guards.py:2611] [62/2] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=1
V0421 03:04:55.535651 47548129527040 torch/_dynamo/guards.py:2611] [62/2] [__recompiles]     - tensor 'L['data']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.554394 47548129527040 torch/_dynamo/guards.py:2611] [63/2] [__recompiles] Recompiling function create in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:472
V0421 03:04:55.554394 47548129527040 torch/_dynamo/guards.py:2611] [63/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.554394 47548129527040 torch/_dynamo/guards.py:2611] [63/2] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=1
V0421 03:04:55.554394 47548129527040 torch/_dynamo/guards.py:2611] [63/2] [__recompiles]     - tensor 'L['data']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.570948 47548129527040 torch/_dynamo/guards.py:2611] [64/2] [__recompiles] Recompiling function __init__ in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:210
V0421 03:04:55.570948 47548129527040 torch/_dynamo/guards.py:2611] [64/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.570948 47548129527040 torch/_dynamo/guards.py:2611] [64/2] [__recompiles]     - tensor 'L['storage']' requires_grad mismatch. expected requires_grad=1
V0421 03:04:55.570948 47548129527040 torch/_dynamo/guards.py:2611] [64/2] [__recompiles]     - tensor 'L['storage']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.589548 47548129527040 torch/_dynamo/guards.py:2611] [65/2] [__recompiles] Recompiling function infer_scheme in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:151
V0421 03:04:55.589548 47548129527040 torch/_dynamo/guards.py:2611] [65/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.589548 47548129527040 torch/_dynamo/guards.py:2611] [65/2] [__recompiles]     - tensor 'L['tensor']' requires_grad mismatch. expected requires_grad=1
V0421 03:04:55.589548 47548129527040 torch/_dynamo/guards.py:2611] [65/2] [__recompiles]     - tensor 'L['tensor']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.632589 47548129527040 torch/_dynamo/guards.py:2611] [68/2] [__recompiles] Recompiling function func in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/ops/spmm.py:213
V0421 03:04:55.632589 47548129527040 torch/_dynamo/guards.py:2611] [68/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.632589 47548129527040 torch/_dynamo/guards.py:2611] [68/2] [__recompiles]     - tensor 'L['x']' requires_grad mismatch. expected requires_grad=1
V0421 03:04:55.632589 47548129527040 torch/_dynamo/guards.py:2611] [68/2] [__recompiles]     - tensor 'L['x']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.646011 47548129527040 torch/_dynamo/guards.py:2611] [70/2] [__recompiles] Recompiling function torch_dynamo_resume_in_gspmm_at_75 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/ops/spmm.py:75
V0421 03:04:55.646011 47548129527040 torch/_dynamo/guards.py:2611] [70/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.646011 47548129527040 torch/_dynamo/guards.py:2611] [70/2] [__recompiles]     - tensor 'L['lhs_data']' requires_grad mismatch. expected requires_grad=1
V0421 03:04:55.646011 47548129527040 torch/_dynamo/guards.py:2611] [70/2] [__recompiles]     - tensor 'L['lhs_data']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.663739 47548129527040 torch/_dynamo/guards.py:2611] [74/2] [__recompiles] Recompiling function forward in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/sparse.py:163
V0421 03:04:55.663739 47548129527040 torch/_dynamo/guards.py:2611] [74/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.663739 47548129527040 torch/_dynamo/guards.py:2611] [74/2] [__recompiles]     - tensor 'L['X']' requires_grad mismatch. expected requires_grad=1
V0421 03:04:55.663739 47548129527040 torch/_dynamo/guards.py:2611] [74/2] [__recompiles]     - tensor 'L['X']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.680340 47548129527040 torch/_dynamo/guards.py:2611] [77/2] [__recompiles] Recompiling function zeros in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:287
V0421 03:04:55.680340 47548129527040 torch/_dynamo/guards.py:2611] [77/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.680340 47548129527040 torch/_dynamo/guards.py:2611] [77/2] [__recompiles]     - L['shape'][0] == 3398                                       
V0421 03:04:55.680340 47548129527040 torch/_dynamo/guards.py:2611] [77/2] [__recompiles]     - L['shape'][0] == 3398                                       
V0421 03:04:55.842346 47548129527040 torch/_dynamo/guards.py:2611] [79/2] [__recompiles] Recompiling function zerocopy_to_dgl_ndarray_for_write in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:454
V0421 03:04:55.842346 47548129527040 torch/_dynamo/guards.py:2611] [79/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.842346 47548129527040 torch/_dynamo/guards.py:2611] [79/2] [__recompiles]     - tensor 'L['input']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.842346 47548129527040 torch/_dynamo/guards.py:2611] [79/2] [__recompiles]     - tensor 'L['input']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.884052 47548129527040 torch/_dynamo/guards.py:2611] [80/2] [__recompiles] Recompiling function check_is_view in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:441
V0421 03:04:55.884052 47548129527040 torch/_dynamo/guards.py:2611] [80/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.884052 47548129527040 torch/_dynamo/guards.py:2611] [80/2] [__recompiles]     - tensor 'L['input']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.884052 47548129527040 torch/_dynamo/guards.py:2611] [80/2] [__recompiles]     - tensor 'L['input']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.895357 47548129527040 torch/_dynamo/guards.py:2611] [81/2] [__recompiles] Recompiling function torch_dynamo_resume_in_check_is_view_at_443 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:443
V0421 03:04:55.895357 47548129527040 torch/_dynamo/guards.py:2611] [81/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.895357 47548129527040 torch/_dynamo/guards.py:2611] [81/2] [__recompiles]     - tensor 'L['input']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.895357 47548129527040 torch/_dynamo/guards.py:2611] [81/2] [__recompiles]     - tensor 'L['input']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.907971 47548129527040 torch/_dynamo/guards.py:2611] [82/2] [__recompiles] Recompiling function torch_dynamo_resume_in_zerocopy_to_dgl_ndarray_for_write_at_461 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/tensor.py:461
V0421 03:04:55.907971 47548129527040 torch/_dynamo/guards.py:2611] [82/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.907971 47548129527040 torch/_dynamo/guards.py:2611] [82/2] [__recompiles]     - tensor 'L['input']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.907971 47548129527040 torch/_dynamo/guards.py:2611] [82/2] [__recompiles]     - tensor 'L['input']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:55.924380 47548129527040 torch/_dynamo/guards.py:2611] [88/1] [__recompiles] Recompiling function forward in /work2/09808/mp46753/frontera/ML_Project/VQGraph/vq.py:569
V0421 03:04:55.924380 47548129527040 torch/_dynamo/guards.py:2611] [88/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:55.924380 47548129527040 torch/_dynamo/guards.py:2611] [88/1] [__recompiles]     - tensor 'L['x']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:56.015160 47548129527040 torch/_dynamo/guards.py:2611] [89/1] [__recompiles] Recompiling function torch_dynamo_resume_in_forward_at_590 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/vq.py:590
V0421 03:04:56.015160 47548129527040 torch/_dynamo/guards.py:2611] [89/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:56.015160 47548129527040 torch/_dynamo/guards.py:2611] [89/1] [__recompiles]     - tensor 'L['___stack0']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:56.080565 47548129527040 torch/_dynamo/guards.py:2611] [90/1] [__recompiles] Recompiling function forward in /work2/09808/mp46753/frontera/ML_Project/VQGraph/vq.py:418
V0421 03:04:56.080565 47548129527040 torch/_dynamo/guards.py:2611] [90/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:56.080565 47548129527040 torch/_dynamo/guards.py:2611] [90/1] [__recompiles]     - tensor 'L['x']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:57.035996 47548129527040 torch/_dynamo/guards.py:2611] [93/1] [__recompiles] Recompiling function torch_dynamo_resume_in_forward_at_432 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/vq.py:432
V0421 03:04:57.035996 47548129527040 torch/_dynamo/guards.py:2611] [93/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:57.035996 47548129527040 torch/_dynamo/guards.py:2611] [93/1] [__recompiles]     - L['shape'][1] == 3398                                       
V0421 03:04:59.677763 47548129527040 torch/_dynamo/guards.py:2611] [94/1] [__recompiles] Recompiling function torch_dynamo_resume_in_forward_at_595 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/vq.py:595
V0421 03:04:59.677763 47548129527040 torch/_dynamo/guards.py:2611] [94/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:59.677763 47548129527040 torch/_dynamo/guards.py:2611] [94/1] [__recompiles]     - tensor 'L['x']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:04:59.929206 47548129527040 torch/_dynamo/guards.py:2611] [95/1] [__recompiles] Recompiling function torch_dynamo_resume_in_forward_at_604 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/vq.py:604
V0421 03:04:59.929206 47548129527040 torch/_dynamo/guards.py:2611] [95/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:04:59.929206 47548129527040 torch/_dynamo/guards.py:2611] [95/1] [__recompiles]     - tensor 'L['x']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:05:00.851714 47548129527040 torch/_dynamo/guards.py:2611] [96/1] [__recompiles] Recompiling function torch_dynamo_resume_in_forward_at_648 in /work2/09808/mp46753/frontera/ML_Project/VQGraph/vq.py:648
V0421 03:05:00.851714 47548129527040 torch/_dynamo/guards.py:2611] [96/1] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:00.851714 47548129527040 torch/_dynamo/guards.py:2611] [96/1] [__recompiles]     - tensor 'L['___stack0']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:05:00.955325 47548129527040 torch/_dynamo/guards.py:2611] [57/3] [__recompiles] Recompiling function __setitem__ in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/view.py:82
V0421 03:05:00.955325 47548129527040 torch/_dynamo/guards.py:2611] [57/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:00.955325 47548129527040 torch/_dynamo/guards.py:2611] [57/3] [__recompiles]     - tensor 'L['val']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:00.955325 47548129527040 torch/_dynamo/guards.py:2611] [57/3] [__recompiles]     - tensor 'L['val']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:05:00.955325 47548129527040 torch/_dynamo/guards.py:2611] [57/3] [__recompiles]     - tensor 'L['val']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:00.975724 47548129527040 torch/_dynamo/guards.py:2611] [61/3] [__recompiles] Recompiling function __setitem__ in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:690
V0421 03:05:00.975724 47548129527040 torch/_dynamo/guards.py:2611] [61/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:00.975724 47548129527040 torch/_dynamo/guards.py:2611] [61/3] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:00.975724 47548129527040 torch/_dynamo/guards.py:2611] [61/3] [__recompiles]     - tensor 'L['data']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:05:00.975724 47548129527040 torch/_dynamo/guards.py:2611] [61/3] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:00.996485 47548129527040 torch/_dynamo/guards.py:2611] [62/3] [__recompiles] Recompiling function update_column in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:772
V0421 03:05:00.996485 47548129527040 torch/_dynamo/guards.py:2611] [62/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:00.996485 47548129527040 torch/_dynamo/guards.py:2611] [62/3] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:00.996485 47548129527040 torch/_dynamo/guards.py:2611] [62/3] [__recompiles]     - tensor 'L['data']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:05:00.996485 47548129527040 torch/_dynamo/guards.py:2611] [62/3] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:01.018203 47548129527040 torch/_dynamo/guards.py:2611] [63/3] [__recompiles] Recompiling function create in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:472
V0421 03:05:01.018203 47548129527040 torch/_dynamo/guards.py:2611] [63/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:01.018203 47548129527040 torch/_dynamo/guards.py:2611] [63/3] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:01.018203 47548129527040 torch/_dynamo/guards.py:2611] [63/3] [__recompiles]     - tensor 'L['data']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:05:01.018203 47548129527040 torch/_dynamo/guards.py:2611] [63/3] [__recompiles]     - tensor 'L['data']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:01.036975 47548129527040 torch/_dynamo/guards.py:2611] [64/3] [__recompiles] Recompiling function __init__ in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:210
V0421 03:05:01.036975 47548129527040 torch/_dynamo/guards.py:2611] [64/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:01.036975 47548129527040 torch/_dynamo/guards.py:2611] [64/3] [__recompiles]     - tensor 'L['storage']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:01.036975 47548129527040 torch/_dynamo/guards.py:2611] [64/3] [__recompiles]     - tensor 'L['storage']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:05:01.036975 47548129527040 torch/_dynamo/guards.py:2611] [64/3] [__recompiles]     - tensor 'L['storage']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:01.057749 47548129527040 torch/_dynamo/guards.py:2611] [65/3] [__recompiles] Recompiling function infer_scheme in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/frame.py:151
V0421 03:05:01.057749 47548129527040 torch/_dynamo/guards.py:2611] [65/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:01.057749 47548129527040 torch/_dynamo/guards.py:2611] [65/3] [__recompiles]     - tensor 'L['tensor']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:01.057749 47548129527040 torch/_dynamo/guards.py:2611] [65/3] [__recompiles]     - tensor 'L['tensor']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:05:01.057749 47548129527040 torch/_dynamo/guards.py:2611] [65/3] [__recompiles]     - tensor 'L['tensor']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:01.105316 47548129527040 torch/_dynamo/guards.py:2611] [68/3] [__recompiles] Recompiling function func in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/ops/spmm.py:213
V0421 03:05:01.105316 47548129527040 torch/_dynamo/guards.py:2611] [68/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:01.105316 47548129527040 torch/_dynamo/guards.py:2611] [68/3] [__recompiles]     - tensor 'L['x']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:01.105316 47548129527040 torch/_dynamo/guards.py:2611] [68/3] [__recompiles]     - tensor 'L['x']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:05:01.105316 47548129527040 torch/_dynamo/guards.py:2611] [68/3] [__recompiles]     - tensor 'L['x']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:01.119842 47548129527040 torch/_dynamo/guards.py:2611] [70/3] [__recompiles] Recompiling function torch_dynamo_resume_in_gspmm_at_75 in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/ops/spmm.py:75
V0421 03:05:01.119842 47548129527040 torch/_dynamo/guards.py:2611] [70/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:01.119842 47548129527040 torch/_dynamo/guards.py:2611] [70/3] [__recompiles]     - tensor 'L['lhs_data']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:01.119842 47548129527040 torch/_dynamo/guards.py:2611] [70/3] [__recompiles]     - tensor 'L['lhs_data']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:05:01.119842 47548129527040 torch/_dynamo/guards.py:2611] [70/3] [__recompiles]     - tensor 'L['lhs_data']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:01.138507 47548129527040 torch/_dynamo/guards.py:2611] [74/3] [__recompiles] Recompiling function forward in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/backend/pytorch/sparse.py:163
V0421 03:05:01.138507 47548129527040 torch/_dynamo/guards.py:2611] [74/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:01.138507 47548129527040 torch/_dynamo/guards.py:2611] [74/3] [__recompiles]     - tensor 'L['X']' requires_grad mismatch. expected requires_grad=0
V0421 03:05:01.138507 47548129527040 torch/_dynamo/guards.py:2611] [74/3] [__recompiles]     - tensor 'L['X']' size mismatch at index 0. expected 3398, actual 3415
V0421 03:05:01.138507 47548129527040 torch/_dynamo/guards.py:2611] [74/3] [__recompiles]     - tensor 'L['X']' requires_grad mismatch. expected requires_grad=0
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/dataloading/dataloader.py:1144: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
V0421 03:05:02.174133 47548129527040 torch/_dynamo/guards.py:2611] [15/2] [__recompiles] Recompiling function _dispatch in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/utils/internal.py:65
V0421 03:05:02.174133 47548129527040 torch/_dynamo/guards.py:2611] [15/2] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:02.174133 47548129527040 torch/_dynamo/guards.py:2611] [15/2] [__recompiles]     - L['data'][0] == 3415                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:02.174133 47548129527040 torch/_dynamo/guards.py:2611] [15/2] [__recompiles]     - L['data'][0] == 3398                                        
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/dataloading/dataloader.py:1144: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
V0421 03:05:06.433195 47548129527040 torch/_dynamo/guards.py:2611] [15/3] [__recompiles] Recompiling function _dispatch in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/utils/internal.py:65
V0421 03:05:06.433195 47548129527040 torch/_dynamo/guards.py:2611] [15/3] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:06.433195 47548129527040 torch/_dynamo/guards.py:2611] [15/3] [__recompiles]     - L['data'][0] == 3436                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:06.433195 47548129527040 torch/_dynamo/guards.py:2611] [15/3] [__recompiles]     - L['data'][0] == 3415                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:06.433195 47548129527040 torch/_dynamo/guards.py:2611] [15/3] [__recompiles]     - L['data'][0] == 3398                                        
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/dataloading/dataloader.py:1144: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
V0421 03:05:10.720672 47548129527040 torch/_dynamo/guards.py:2611] [15/4] [__recompiles] Recompiling function _dispatch in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/utils/internal.py:65
V0421 03:05:10.720672 47548129527040 torch/_dynamo/guards.py:2611] [15/4] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:10.720672 47548129527040 torch/_dynamo/guards.py:2611] [15/4] [__recompiles]     - L['data'][0] == 3338                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:10.720672 47548129527040 torch/_dynamo/guards.py:2611] [15/4] [__recompiles]     - L['data'][0] == 3436                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:10.720672 47548129527040 torch/_dynamo/guards.py:2611] [15/4] [__recompiles]     - L['data'][0] == 3415                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:10.720672 47548129527040 torch/_dynamo/guards.py:2611] [15/4] [__recompiles]     - L['data'][0] == 3398                                        
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/dataloading/dataloader.py:1144: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
V0421 03:05:15.010782 47548129527040 torch/_dynamo/guards.py:2611] [15/5] [__recompiles] Recompiling function _dispatch in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/utils/internal.py:65
V0421 03:05:15.010782 47548129527040 torch/_dynamo/guards.py:2611] [15/5] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:15.010782 47548129527040 torch/_dynamo/guards.py:2611] [15/5] [__recompiles]     - L['data'][0] == 3420                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:15.010782 47548129527040 torch/_dynamo/guards.py:2611] [15/5] [__recompiles]     - L['data'][0] == 3338                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:15.010782 47548129527040 torch/_dynamo/guards.py:2611] [15/5] [__recompiles]     - L['data'][0] == 3436                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:15.010782 47548129527040 torch/_dynamo/guards.py:2611] [15/5] [__recompiles]     - L['data'][0] == 3415                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:15.010782 47548129527040 torch/_dynamo/guards.py:2611] [15/5] [__recompiles]     - L['data'][0] == 3398                                        
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/dataloading/dataloader.py:1144: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
V0421 03:05:19.303658 47548129527040 torch/_dynamo/guards.py:2611] [15/6] [__recompiles] Recompiling function _dispatch in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/utils/internal.py:65
V0421 03:05:19.303658 47548129527040 torch/_dynamo/guards.py:2611] [15/6] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:19.303658 47548129527040 torch/_dynamo/guards.py:2611] [15/6] [__recompiles]     - L['data'][0] == 3401                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:19.303658 47548129527040 torch/_dynamo/guards.py:2611] [15/6] [__recompiles]     - L['data'][0] == 3420                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:19.303658 47548129527040 torch/_dynamo/guards.py:2611] [15/6] [__recompiles]     - L['data'][0] == 3338                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:19.303658 47548129527040 torch/_dynamo/guards.py:2611] [15/6] [__recompiles]     - L['data'][0] == 3436                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:19.303658 47548129527040 torch/_dynamo/guards.py:2611] [15/6] [__recompiles]     - L['data'][0] == 3415                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:19.303658 47548129527040 torch/_dynamo/guards.py:2611] [15/6] [__recompiles]     - L['data'][0] == 3398                                        
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/dataloading/dataloader.py:1144: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
V0421 03:05:23.605390 47548129527040 torch/_dynamo/guards.py:2611] [15/7] [__recompiles] Recompiling function _dispatch in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/utils/internal.py:65
V0421 03:05:23.605390 47548129527040 torch/_dynamo/guards.py:2611] [15/7] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:23.605390 47548129527040 torch/_dynamo/guards.py:2611] [15/7] [__recompiles]     - L['data'][0] == 3433                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:23.605390 47548129527040 torch/_dynamo/guards.py:2611] [15/7] [__recompiles]     - L['data'][0] == 3401                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:23.605390 47548129527040 torch/_dynamo/guards.py:2611] [15/7] [__recompiles]     - L['data'][0] == 3420                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:23.605390 47548129527040 torch/_dynamo/guards.py:2611] [15/7] [__recompiles]     - L['data'][0] == 3338                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:23.605390 47548129527040 torch/_dynamo/guards.py:2611] [15/7] [__recompiles]     - L['data'][0] == 3436                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:23.605390 47548129527040 torch/_dynamo/guards.py:2611] [15/7] [__recompiles]     - L['data'][0] == 3415                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:23.605390 47548129527040 torch/_dynamo/guards.py:2611] [15/7] [__recompiles]     - L['data'][0] == 3398                                        
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/dataloading/dataloader.py:1144: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
V0421 03:05:27.881729 47548129527040 torch/_dynamo/guards.py:2611] [15/8] [__recompiles] Recompiling function _dispatch in /work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/utils/internal.py:65
V0421 03:05:27.881729 47548129527040 torch/_dynamo/guards.py:2611] [15/8] [__recompiles]     triggered by the following guard failure(s):
V0421 03:05:27.881729 47548129527040 torch/_dynamo/guards.py:2611] [15/8] [__recompiles]     - L['data'][0] == 3419                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:27.881729 47548129527040 torch/_dynamo/guards.py:2611] [15/8] [__recompiles]     - L['data'][0] == 3433                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:27.881729 47548129527040 torch/_dynamo/guards.py:2611] [15/8] [__recompiles]     - L['data'][0] == 3401                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:27.881729 47548129527040 torch/_dynamo/guards.py:2611] [15/8] [__recompiles]     - L['data'][0] == 3420                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:27.881729 47548129527040 torch/_dynamo/guards.py:2611] [15/8] [__recompiles]     - L['data'][0] == 3338                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:27.881729 47548129527040 torch/_dynamo/guards.py:2611] [15/8] [__recompiles]     - L['data'][0] == 3436                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:27.881729 47548129527040 torch/_dynamo/guards.py:2611] [15/8] [__recompiles]     - L['data'][0] == 3415                                          # _dynamo/output_graph.py:452 in init_ambient_guards
V0421 03:05:27.881729 47548129527040 torch/_dynamo/guards.py:2611] [15/8] [__recompiles]     - L['data'][0] == 3398                                        
W0421 03:05:27.881972 47548129527040 torch/_dynamo/convert_frame.py:762] [15/8] torch._dynamo hit config.cache_size_limit (8)
W0421 03:05:27.881972 47548129527040 torch/_dynamo/convert_frame.py:762] [15/8]    function: '_dispatch' (/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/utils/internal.py:65)
W0421 03:05:27.881972 47548129527040 torch/_dynamo/convert_frame.py:762] [15/8]    last reason: L['data'][0] == 3398                                        
W0421 03:05:27.881972 47548129527040 torch/_dynamo/convert_frame.py:762] [15/8] To log all recompilation reasons, use TORCH_LOGS="recompiles".
W0421 03:05:27.881972 47548129527040 torch/_dynamo/convert_frame.py:762] [15/8] To diagnose recompilation issues, see https://pytorch.org/docs/main/torch.compiler_troubleshooting.html.
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/dataloading/dataloader.py:1144: DGLWarning: Dataloader CPU affinity opt is not enabled, consider switching it on (see enable_cpu_affinity() or CPU best practices for DGL [https://docs.dgl.ai/tutorials/cpu/cpu_best_practises.html])
  dgl_warning(
/work2/09808/mp46753/frontera/ML_Project/miniconda3/envs/txgnn_env/lib/python3.8/site-packages/dgl/heterograph.py:92: DGLWarning: Recommend creating graphs by `dgl.graph(data)` instead of `dgl.DGLGraph(data)`.
  dgl_warning(
Compiling model with torch.compile()...
Saved sparsity snapshot to outputs_compiled/tran/a-computer/SAGE/seed_0/sparsity_before.csv
                               layer_name  num_elements  sparsity
0  _orig_mod.encoder.graph_layer_1.weight        588289       0.0
1    _orig_mod.encoder.graph_layer_1.bias           767     100.0
2  _orig_mod.encoder.graph_layer_2.weight         98176       0.0
3    _orig_mod.encoder.graph_layer_2.bias           128     100.0
4      _orig_mod.encoder.decoder_1.weight        588289       0.0
5        _orig_mod.encoder.decoder_1.bias           767       0.0
6      _orig_mod.encoder.decoder_2.weight        588289       0.0
7        _orig_mod.encoder.decoder_2.bias           767       0.0
8         _orig_mod.encoder.linear.weight          1280       0.0
9           _orig_mod.encoder.linear.bias            10       0.0
Saved sparsity snapshot to outputs_compiled/tran/a-computer/SAGE/seed_0/sparsity_after.csv
                               layer_name  num_elements   sparsity
0  _orig_mod.encoder.graph_layer_1.weight        588289  10.362594
1    _orig_mod.encoder.graph_layer_1.bias           767   2.477184
2  _orig_mod.encoder.graph_layer_2.weight         98176  14.627811
3    _orig_mod.encoder.graph_layer_2.bias           128   0.000000
4      _orig_mod.encoder.decoder_1.weight        588289   0.035187
5        _orig_mod.encoder.decoder_1.bias           767   0.000000
6      _orig_mod.encoder.decoder_2.weight        588289  70.582486
7        _orig_mod.encoder.decoder_2.bias           767  49.152542
8         _orig_mod.encoder.linear.weight          1280   0.546875
9           _orig_mod.encoder.linear.bias            10   0.000000
Saved forward timing report to outputs_compiled/tran/a-computer/SAGE/seed_0/forward_times.csv
                         layer_name  avg_forward_time_ms  num_calls
0         _orig_mod.encoder.dropout             0.000602      14027
1   _orig_mod.encoder.graph_layer_1             0.000891      14027
2   _orig_mod.encoder.graph_layer_2             0.000741      14027
3       _orig_mod.encoder.decoder_1             0.000700      14027
4       _orig_mod.encoder.decoder_2             0.000663      14027
5          _orig_mod.encoder.linear             0.000298      14027
6   _orig_mod.encoder.vq.project_in             0.000624      14027
7  _orig_mod.encoder.vq.project_out             0.022897      14027
8    _orig_mod.encoder.vq._codebook             0.000921      14027
CPU Memory Usage: 1303.28 MB
Max GPU Memory Used: 2082.45 MB
